product-os/jellyfish-plugin-incidents

- package.json
> Update worker to 24

- .editorconfig
- .github/workflows/publish-docs.yml
- .gitignore
- .npmrc
- jest.config.js
- package.json
- tsconfig.build.json
- tsconfig.json
- tslint.json
> Drop @balena/jellyfish-config

- lib/index.ts
- package.json
- test/unit/index.spec.ts
- tsconfig.json
> Drop plugin-channels

- docker-compose.test.yml
- docker-compose.yml
- lib/index.ts
- lib/integrations/index.ts
- lib/integrations/nodeping.ts
- package.json
- test/integration/nodeping-translate.spec.ts
- test/integration/webhooks/index.ts
- test/integration/webhooks/notification/01.json
- test/integration/webhooks/notification/expected.json
> Add Nodeping integration

- .resinci.yml
- lib/contracts/incident.ts
- lib/index.ts
- lib/integrations/nodeping.ts
- lib/types/contracts/incident.ts
- lib/types/contracts/index.ts
- lib/types/contracts/post-mortem.ts
- lib/types/index.ts
- test/integration/webhooks/down-then-up/01.json
- test/integration/webhooks/down-then-up/02.json
- test/integration/webhooks/down-then-up/expected.json
- test/integration/webhooks/down/01.json
- test/integration/webhooks/down/expected.json
- test/integration/webhooks/index.ts
> Improve Nodeping integration, add types

- lib/integrations/statuspage.ts
- package.json
- test/integration/statuspage-translate.spec.ts
- test/integration/webhooks/major-outage-then-resolved/01.json
- test/integration/webhooks/major-outage-then-resolved/02.json
- test/integration/webhooks/major-outage-then-resolved/expected.json
- test/integration/webhooks/major-outage-then-resolved/stubs/1/v-1-pages-foobar-incidents-yf-8-nfxmhb-2-jg.json
- test/integration/webhooks/major-outage-then-resolved/stubs/2/v-1-pages-foobar-incidents-yf-8-nfxmhb-2-jg.json
- test/integration/webhooks/major-outage/01.json
- test/integration/webhooks/major-outage/expected.json
- test/integration/webhooks/major-outage/stubs/1/v-1-pages-foobar-incidents-yf-8-nfxmhb-2-jg.json
- test/unit/integrations/statuspage.spec.ts
> Add Statuspage webhook validation

- lib/environment.ts
- lib/integrations/statuspage.ts
- package.json
- test/integration/statuspage-translate.spec.ts
Change-type: major
---
Resolves https://github.com/product-os/jellyfish-plugin-incidents/issues/132
Resolves https://github.com/product-os/jellyfish-plugin-incidents/issues/131
> Drop jellyfish-environment, support multiple pages

- test/unit/environment.spec.ts
> Add environment unit test

- lib/environment.ts
- test/unit/environment/defaults.spec.ts
> Improve environment variable logic

- package.json
> Update to worker 32.0.1

- lib/contracts/incident.ts
- lib/contracts/post-mortem.ts
> Simplify incident and post-mortem contracts

- lib/actions/action-integration-statuspage-import-incident.ts
- test/integration/actions/action-integration-statuspage-import-incident.spec.ts
> Create ping message on new incident

- lib/actions/action-integration-statuspage-import-incident.ts
- lib/integrations/statuspage.ts
- test/integration/actions/action-integration-statuspage-import-incident.spec.ts
- test/unit/integrations/statuspage.spec.ts
Create incident contracts from incoming Statuspage component webhooks
***
Will test manually on personal VPS before merging
> Handle component update webhooks

- lib/actions/action-integration-statuspage-import-incident.ts
- test/unit/actions/action-integration-statuspage-import-incident.spec.ts
> Add more docs/tests

- lib/actions/action-integration-statuspage-import-incident.ts
- test/integration/actions/action-integration-statuspage-import-incident.spec.ts
- test/unit/actions/action-integration-statuspage-import-incident.spec.ts
> Add more tests

- README.md
- lib/actions/action-integration-statuspage-import-incident.ts
- test/integration/actions/action-integration-statuspage-import-incident.spec.ts
> Create ping message on thread, update README

- lib/actions/action-integration-statuspage-import-incident.ts
- test/integration/actions/action-integration-statuspage-import-incident.spec.ts
> Name thread, add details to ping

- lib/actions/action-integration-statuspage-import-incident.ts
> Add link to incident contract in ping

- README.md
- docker-compose.test.yml
- package.json
> CI: Drop npm test:compose script

- .github/workflows/codeql-analysis.yml
> Security: Add CodeQL analysis workflow

- .github/renovate.json
- .github/workflows/codeql-analysis.yml
- docker-compose.test.yml
- docker-compose.yml
- package.json
- tsconfig.build.json
- tsconfig.json
- tslint.json
> Dev: Use prettier for json/yml

- package.json
> Dev: Fix prettier npm scripts

- .prettierignore
> Dev: Add .prettierignore

- lib/actions/action-integration-statuspage-import-incident.ts
> Always use hubot user for ping
